# Generated by Django 4.1.3 on 2023-04-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_admin_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinfo",
            name="companyTags",
            field=models.CharField(default="", max_length=650, verbose_name="公司福利"),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="createTime",
            field=models.DateField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="jobinfo",
            name="detailUrl",
            field=models.CharField(default="", max_length=300, verbose_name="详情页面"),
        ),
    ]
